# Generated by Django 6.1 on 2026-09-29 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('alert_rule_id', models.CharField(max_length=50, unique=True, verbose_name='Código de regla de alerta')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la regla')),
                ('severity', models.CharField(max_length=50, verbose_name='Severidad')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de medida')),
                ('min_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Límite mínimo')),
                ('max_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Límite máximo')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Regla de alerta',
                'verbose_name_plural': 'Reglas de alerta',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('catalog_id', models.CharField(max_length=50, unique=True, verbose_name='Código de catálogo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('device_id', models.CharField(max_length=50, unique=True, verbose_name='Código de dispositivo')),
                ('internal_name', models.CharField(max_length=150, verbose_name='Nombre interno')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('reference_power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Potencia de referencia (kW)')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de serie')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='organizations.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['internal_name'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('history_id', models.CharField(max_length=50, unique=True, verbose_name='Código de historial')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de término')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='histories', to='devices.device', verbose_name='Dispositivo')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='histories', to='organizations.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('maintenance_request_id', models.CharField(max_length=50, unique=True, verbose_name='Código de solicitud')),
                ('request_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de solicitud')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo')),
                ('priority', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prioridad')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha programada')),
                ('actual_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha real de ejecución')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('actions_text', models.TextField(blank=True, null=True, verbose_name='Acciones realizadas')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='devices.device', verbose_name='Dispositivo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='organizations.organization', verbose_name='Organización')),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Solicitud de mantenimiento',
                'verbose_name_plural': 'Solicitudes de mantenimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('measurement_id', models.CharField(max_length=50, unique=True, verbose_name='Código de medición')),
                ('value', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidad de medida')),
                ('datetime', models.DateTimeField(verbose_name='Fecha y hora de lectura')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('origin', models.CharField(max_length=50, verbose_name='Origen')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='devices.device', verbose_name='Dispositivo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to=settings.AUTH_USER_MODEL, verbose_name='Usuario registrador')),
            ],
            options={
                'verbose_name': 'Medición',
                'verbose_name_plural': 'Mediciones',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('alert_event_id', models.CharField(max_length=50, unique=True, verbose_name='Código de evento de alerta')),
                ('min_limit_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Límite mínimo (snapshot)')),
                ('max_limit_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Límite máximo (snapshot)')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reconocimiento')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_alert_events', to=settings.AUTH_USER_MODEL, verbose_name='Reconocido por')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_alert_events', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_events', to='devices.alertrule', verbose_name='Regla de alerta')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_events', to='devices.device', verbose_name='Dispositivo')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_events', to='devices.measurement', verbose_name='Medición relacionada')),
            ],
            options={
                'verbose_name': 'Evento de alerta',
                'verbose_name_plural': 'Eventos de alerta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('product_id', models.CharField(max_length=50, unique=True, verbose_name='Código de producto')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Consumo (kWh)')),
                ('manufacter', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fabricante')),
                ('model', models.CharField(blank=True, max_length=150, null=True, verbose_name='Modelo')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='devices.catalog', verbose_name='Catálogo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_rules', to='devices.product', verbose_name='Producto'),
        ),
    ]
