# Generated by Django 6.1.1 on 2026-10-01 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manufacter',
            new_name='manufacturer',
        ),
    ]
