# Generated by Django 6.1 on 2026-09-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('organization_id', models.CharField(max_length=50, unique=True, verbose_name='Código de organización')),
                ('legal_name', models.CharField(max_length=150, verbose_name='Razón social')),
                ('comercial_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre comercial')),
                ('contact', models.CharField(blank=True, max_length=150, null=True, verbose_name='Contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('tax', models.CharField(max_length=50, verbose_name='Identificación fiscal (RUT/Tax ID)')),
                ('status', models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('department_id', models.CharField(max_length=50, unique=True, verbose_name='Código de departamento')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del departamento')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('status', models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('user_id', models.CharField(max_length=50, unique=True, verbose_name='Código de usuario')),
                ('username', models.CharField(max_length=150, verbose_name='Nombre de usuario')),
                ('rut', models.CharField(max_length=20, verbose_name='RUT')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('role', models.CharField(max_length=50, verbose_name='Rol')),
                ('status', models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organizations.department', verbose_name='Departamento')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_departments', to='organizations.user', verbose_name='Encargado / Responsable'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('zone_id', models.CharField(max_length=50, unique=True, verbose_name='Código de zona')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la zona')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('status', models.BooleanField(blank=True, default=True, null=True, verbose_name='Activa')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='organizations.department', verbose_name='Departamento')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['name'],
            },
        ),
    ]
